# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - "feature/oauth1"
  script:
    - cp -rf /projects/web-conf/oauth.env.local ./.env.local  # 同步配置文件
    # - standalone
    - npm config set registry https://registry.npm.taobao.org
    - npm i
    - npm run build
    - cp -rf ./public ./.next/standalone/ && cd ./.next && cp -rf ./static ./standalone/.next/ && cd ./standalone && tar cf oahtu2.tar ./* .[!.]*
    - scp oahtu2.tar root@121.37.83.16:/www
    - echo "Application successfully build."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - "feature/oauth1"
  environment: production
  script:
    -  ssh root@121.37.83.16 "tar -xvf /www/oahtu2.tar -C /www/edms-oauth && rm /www/oahtu2.tar && supervisorctl restart oauth-node"
    - echo "Application successfully deployed."
